[package]
name = "nomadapi"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
