[package]
name = "examplebin"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
schemars = "0.8.12"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
