name: Push

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: cargo-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-

      - name: Install cargo extensions
        run: cargo install --locked cargo-deny
        shell: bash

      - name: cargo fmt
        run: cargo fmt --all -- --check
        shell: bash

      - name: cargo clippy
        run: cargo clippy
        shell: bash

      - name: cargo build
        run: cargo build
        shell: bash

      - name: cargo test
        run: cargo test -- --nocapture
        shell: bash

      - name: cargo deny
        run: cargo deny check
        shell: bash

      - name: cargo package
        run: cargo package
        shell: bash
